server:
  address: "gateway:12345"
loop:
  amount: 5
  period: "50ms"
log:
  level: "INFO"
batch:
  maxAmount: 100
files:
  - "movies.csv"
  - "ratings.csv"
  - "credits.csv"
query:
  # ALL: 0, Q1: 1, Q2: 2, Q3: 3, Q4: 4
  number: 0
